protocols: Handle the case when a weak protocol descriptor symbol is undefined
frida/frida-swift-bridge pull request #14
Opened 2023-10-22 16:44 UTC by hot3eed

**Background**
An externally-defined protocol that's imported as a weak symbol (e.g. for backward compatibility) might be undefined on some systems. Currently the bridge would crash in this case since it's trying to dereference a null pointer.

**Changes**
- Add an internal API for extracting a protocol name from its demangled conformance descriptor name.
- Handle a null protocol descriptor pointer.

**How it was tested**
A hello-world SwiftUI app built using Xcode 15.0 (15A240d) on macOS 13.5.2 that was crashing before this change.

2023-10-23 16:15 UTC, oleavr requested changes
Yay, great catch! 🔥🙌🏻 Thanks! ❤️

2023-10-23 16:15 UTC, oleavr commented on lib/macho.ts
> +            conformance descritpor's symbol. */
Typo

2023-10-23 16:15 UTC, oleavr commented on lib/macho.ts
> +            if (protocolName == null) {
Should always use strict equality checks

2023-10-23 16:15 UTC, oleavr commented on lib/symbols.ts
> +    if (matches == null || matches.length != 2) {
- Equality checks should be strict.
- I guess there's no need to check the length, since there's only one group?

2023-11-01 20:03 UTC, hot3eed commented
@oleavr Thanks for the review! Any other comments you'd like to be addressed?

2023-11-03 09:53 UTC, merged

2023-11-03 09:54 UTC, oleavr commented
@hot3eed All good, just me being bad at context-switching — sorry for the delay! 😅